In [1]:
import numpy as np
from numpy import array

In [2]:
#Creating Arrays
#Create a list and convert it into a numpy array
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [3]:
#Or just pass in a list directly
y = np.array([4,5,6])
y

array([4, 5, 6])

In [4]:
#Pass in a list of lists to create a multidimensional array
m = np.array([[7,8,9],
             [10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [5]:
#Use the shape method to find the dimensions of the array. (rows,columns)
m.shape

(2, 3)

In [7]:
#Arrange returns evenly spaced values within a given interval
n = np.arange(0, 30, 2)    #start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [11]:
#reshape() : returns an array with same data with a new shape
n = n.reshape(3, 5)   # a reshaped array to be 3x5
print(n)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


In [10]:
# reshape() function

arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print("Array before using reshape() function : \n",arr)

new_arr = arr.reshape(4,3)
print("\nArray after using reshape() function : \n",new_arr)

Array before using reshape() function : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array after using reshape() function : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
#linspace() : returns evenly spaced numbers over a specified interval
o = np.linspace(0, 90, 12)   #returns 12 evenly spaced values from 0 to 90
o

array([ 0.        ,  8.18181818, 16.36363636, 24.54545455, 32.72727273,
       40.90909091, 49.09090909, 57.27272727, 65.45454545, 73.63636364,
       81.81818182, 90.        ])

In [9]:
#resize changes the shape and size of array in-place.
o.resize(4,3)
o

array([[ 0.        ,  8.18181818, 16.36363636],
       [24.54545455, 32.72727273, 40.90909091],
       [49.09090909, 57.27272727, 65.45454545],
       [73.63636364, 81.81818182, 90.        ]])

In [10]:
#onesreturns a new array of given shape and type, filled with ones.
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
#zeros returns a new array of given shape and type, filled with zeros.
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
#eye returns a 2-D arraynwith ones on the diagonal and zeros elsewhere.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#diag extracts a diagonal or constructs a diagonal array.
y = np.array([4, 5, 6, 7])
np.diag(y)

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

In [14]:
#Create an array using repeating list (or see np.title)
np.array([[1, 2, 3]] * 3)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [15]:
#Repeat elements of an array using repeat.
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [18]:
np.repeat([[18, 21, 22]],3)

array([18, 18, 18, 21, 21, 21, 22, 22, 22])

In [19]:
#Numpy Array with floatinf point
np.array([1.0, 4.2, 3.5, 2.5])

array([1. , 4.2, 3.5, 2.5])

In [20]:
#Create a length - 10 integer array filled with zeros
np.zeros(10, )

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])